# Generated by Django 6.0.4 on 2026-04-30 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production_app", "0006_ev_v3_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoringHost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MonitoringStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MonitoringItem",
            fields=[
                ("itemid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                ("units", models.CharField(blank=True, max_length=40, null=True)),
                ("exclude_from_station_summary", models.BooleanField(default=False)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="production_app.monitoringhost",
                    ),
                ),
            ],
            options={
                "ordering": ["itemid"],
            },
        ),
        migrations.AddField(
            model_name="monitoringhost",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hosts",
                to="production_app.monitoringstation",
            ),
        ),
    ]
